# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_woop_nolayout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1472, 865)
        MainWindow.setMinimumSize(QtCore.QSize(1472, 865))
        MainWindow.setMaximumSize(QtCore.QSize(1472, 865))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1051, 791))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_LID1 = QtGui.QWidget()
        self.tab_LID1.setObjectName(_fromUtf8("tab_LID1"))
        self.widget_LID1 = Canvas(self.tab_LID1)
        self.widget_LID1.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID1.setObjectName(_fromUtf8("widget_LID1"))
        self.tabWidget.addTab(self.tab_LID1, _fromUtf8(""))
        self.tab_LID2 = QtGui.QWidget()
        self.tab_LID2.setObjectName(_fromUtf8("tab_LID2"))
        self.widget_LID2 = Canvas(self.tab_LID2)
        self.widget_LID2.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID2.setObjectName(_fromUtf8("widget_LID2"))
        self.tabWidget.addTab(self.tab_LID2, _fromUtf8(""))
        self.tab_LID3 = QtGui.QWidget()
        self.tab_LID3.setObjectName(_fromUtf8("tab_LID3"))
        self.widget_LID3 = Canvas(self.tab_LID3)
        self.widget_LID3.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID3.setObjectName(_fromUtf8("widget_LID3"))
        self.tabWidget.addTab(self.tab_LID3, _fromUtf8(""))
        self.tab_LID4 = QtGui.QWidget()
        self.tab_LID4.setObjectName(_fromUtf8("tab_LID4"))
        self.widget_LID4 = Canvas(self.tab_LID4)
        self.widget_LID4.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID4.setObjectName(_fromUtf8("widget_LID4"))
        self.tabWidget.addTab(self.tab_LID4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.widget_LID5 = Canvas(self.tab_5)
        self.widget_LID5.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID5.setObjectName(_fromUtf8("widget_LID5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.widget_LID6 = Canvas(self.tab_6)
        self.widget_LID6.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID6.setObjectName(_fromUtf8("widget_LID6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.widget_LID7 = Canvas(self.tab_7)
        self.widget_LID7.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID7.setObjectName(_fromUtf8("widget_LID7"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.widget_LID8 = Canvas(self.tab_8)
        self.widget_LID8.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID8.setObjectName(_fromUtf8("widget_LID8"))
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.widget_LID_ALL = Canvas(self.tab_9)
        self.widget_LID_ALL.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID_ALL.setObjectName(_fromUtf8("widget_LID_ALL"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.widget_MIR = Canvas(self.tab_10)
        self.widget_MIR.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_MIR.setObjectName(_fromUtf8("widget_MIR"))
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(1070, 610, 381, 191))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(1070, 10, 391, 591))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 211, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_newpulse = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_newpulse.setObjectName(_fromUtf8("checkBox_newpulse"))
        self.gridLayout.addWidget(self.checkBox_newpulse, 0, 2, 1, 1)
        self.button_check_pulse = QtGui.QPushButton(self.groupBox_3)
        self.button_check_pulse.setObjectName(_fromUtf8("button_check_pulse"))
        self.gridLayout.addWidget(self.button_check_pulse, 2, 2, 1, 1)
        self.comboBox_readuid = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_readuid.setEditable(True)
        self.comboBox_readuid.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.comboBox_readuid.setObjectName(_fromUtf8("comboBox_readuid"))
        self.gridLayout.addWidget(self.comboBox_readuid, 1, 1, 1, 2)
        self.lineEdit_jpn = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_jpn.setText(_fromUtf8(""))
        self.lineEdit_jpn.setObjectName(_fromUtf8("lineEdit_jpn"))
        self.gridLayout.addWidget(self.lineEdit_jpn, 0, 0, 1, 2)
        self.button_read_pulse = QtGui.QPushButton(self.groupBox_3)
        self.button_read_pulse.setObjectName(_fromUtf8("button_read_pulse"))
        self.gridLayout.addWidget(self.button_read_pulse, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox.setGeometry(QtCore.QRect(230, 20, 145, 199))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButton_storeData = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_storeData.setObjectName(_fromUtf8("radioButton_storeData"))
        self.gridLayout_3.addWidget(self.radioButton_storeData, 0, 0, 1, 1)
        self.radioButton_storeSF = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_storeSF.setObjectName(_fromUtf8("radioButton_storeSF"))
        self.gridLayout_3.addWidget(self.radioButton_storeSF, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_writeuid = QtGui.QComboBox(self.groupBox)
        self.comboBox_writeuid.setEditable(True)
        self.comboBox_writeuid.setObjectName(_fromUtf8("comboBox_writeuid"))
        self.gridLayout_5.addWidget(self.comboBox_writeuid, 2, 0, 1, 1)
        self.button_save = QtGui.QPushButton(self.groupBox)
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.gridLayout_5.addWidget(self.button_save, 3, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 230, 105, 124))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton_plot = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_plot.setObjectName(_fromUtf8("pushButton_plot"))
        self.gridLayout_6.addWidget(self.pushButton_plot, 0, 0, 1, 1)
        self.pushButton_zoom = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_zoom.setObjectName(_fromUtf8("pushButton_zoom"))
        self.gridLayout_6.addWidget(self.pushButton_zoom, 1, 0, 1, 1)
        self.pushButton_reset = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_reset.setObjectName(_fromUtf8("pushButton_reset"))
        self.gridLayout_6.addWidget(self.pushButton_reset, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_5.setGeometry(QtCore.QRect(230, 230, 151, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_2ndtrace = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_2ndtrace.setObjectName(_fromUtf8("comboBox_2ndtrace"))
        self.gridLayout_7.addWidget(self.comboBox_2ndtrace, 0, 0, 1, 1)
        self.button_normalize = QtGui.QPushButton(self.groupBox_5)
        self.button_normalize.setObjectName(_fromUtf8("button_normalize"))
        self.gridLayout_7.addWidget(self.button_normalize, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 360, 155, 220))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_totcorr = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_totcorr.setObjectName(_fromUtf8("lineEdit_totcorr"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEdit_totcorr)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_mancorr = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_mancorr.setObjectName(_fromUtf8("lineEdit_mancorr"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEdit_mancorr)
        self.pushButton_apply = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_apply.setObjectName(_fromUtf8("pushButton_apply"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_apply)
        self.pushButton_undo = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_undo.setObjectName(_fromUtf8("pushButton_undo"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.pushButton_undo)
        self.pushButton_makeperm = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_makeperm.setObjectName(_fromUtf8("pushButton_makeperm"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.pushButton_makeperm)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 370, 91, 109))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.radioButton_statusflag_0 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_statusflag_0.setObjectName(_fromUtf8("radioButton_statusflag_0"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.radioButton_statusflag_0)
        self.radioButton_statusflag_3 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_statusflag_3.setObjectName(_fromUtf8("radioButton_statusflag_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.radioButton_statusflag_3)
        self.radioButton_statusflag_1 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_statusflag_1.setObjectName(_fromUtf8("radioButton_statusflag_1"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.radioButton_statusflag_1)
        self.radioButton_statusflag_4 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_statusflag_4.setObjectName(_fromUtf8("radioButton_statusflag_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.radioButton_statusflag_4)
        self.radioButton_statusflag_2 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_statusflag_2.setObjectName(_fromUtf8("radioButton_statusflag_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.radioButton_statusflag_2)
        self.radioButton_statusflag_5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_statusflag_5.setObjectName(_fromUtf8("radioButton_statusflag_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.radioButton_statusflag_5)
        self.exit_button = QtGui.QPushButton(self.groupBox_8)
        self.exit_button.setGeometry(QtCore.QRect(240, 550, 84, 25))
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1472, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>LID1</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID1), _translate("MainWindow", "LID1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID2), _translate("MainWindow", "LID2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID3), _translate("MainWindow", "LID3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID4), _translate("MainWindow", "LID4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "LID5", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "LID6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "LIF7", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "LID8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "LID ALL", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "MIR", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "KG1 woop", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Input", None))
        self.checkBox_newpulse.setText(_translate("MainWindow", "New pulse", None))
        self.button_check_pulse.setText(_translate("MainWindow", "check Status", None))
        self.button_read_pulse.setText(_translate("MainWindow", "Load", None))
        self.label.setText(_translate("MainWindow", "read uid", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Record data", None))
        self.radioButton_storeData.setText(_translate("MainWindow", "Data", None))
        self.radioButton_storeSF.setText(_translate("MainWindow", "Status Flag", None))
        self.label_2.setText(_translate("MainWindow", "write uid", None))
        self.button_save.setText(_translate("MainWindow", "Save", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plot", None))
        self.pushButton_plot.setText(_translate("MainWindow", "plot", None))
        self.pushButton_zoom.setText(_translate("MainWindow", "zoom", None))
        self.pushButton_reset.setText(_translate("MainWindow", "zoom reset", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Second Trace", None))
        self.button_normalize.setText(_translate("MainWindow", "normalize", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Corrections", None))
        self.label_3.setText(_translate("MainWindow", "Total Corrections", None))
        self.label_4.setText(_translate("MainWindow", "Manual Correction", None))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply", None))
        self.pushButton_undo.setText(_translate("MainWindow", "Undo", None))
        self.pushButton_makeperm.setText(_translate("MainWindow", "Make Permanent", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Status Flag", None))
        self.radioButton_statusflag_0.setText(_translate("MainWindow", "0", None))
        self.radioButton_statusflag_3.setText(_translate("MainWindow", "3", None))
        self.radioButton_statusflag_1.setText(_translate("MainWindow", "1", None))
        self.radioButton_statusflag_4.setText(_translate("MainWindow", "4", None))
        self.radioButton_statusflag_2.setText(_translate("MainWindow", "2", None))
        self.radioButton_statusflag_5.setText(_translate("MainWindow", "5", None))
        self.exit_button.setText(_translate("MainWindow", "exit", None))

from canvas import Canvas
