# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_woop_layout_manualcorrection_widget_bigger_log.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CORMAT_py(object):
    def setupUi(self, CORMAT_py):
        CORMAT_py.setObjectName("CORMAT_py")
        CORMAT_py.resize(1348, 871)
        self.centralwidget = QtWidgets.QWidget(CORMAT_py)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(724, 807))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_LID1 = QtWidgets.QWidget()
        self.tab_LID1.setObjectName("tab_LID1")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_LID1)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.widget_LID1 = Canvas(self.tab_LID1)
        self.widget_LID1.setObjectName("widget_LID1")
        self.gridLayout_20.addWidget(self.widget_LID1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_LID1, "")
        self.tab_LID2 = QtWidgets.QWidget()
        self.tab_LID2.setObjectName("tab_LID2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_LID2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.widget_LID2 = Canvas(self.tab_LID2)
        self.widget_LID2.setObjectName("widget_LID2")
        self.gridLayout_19.addWidget(self.widget_LID2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_LID2, "")
        self.tab_LID3 = QtWidgets.QWidget()
        self.tab_LID3.setObjectName("tab_LID3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_LID3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.widget_LID3 = Canvas(self.tab_LID3)
        self.widget_LID3.setObjectName("widget_LID3")
        self.gridLayout_18.addWidget(self.widget_LID3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_LID3, "")
        self.tab_LID4 = QtWidgets.QWidget()
        self.tab_LID4.setObjectName("tab_LID4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_LID4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.widget_LID4 = Canvas(self.tab_LID4)
        self.widget_LID4.setObjectName("widget_LID4")
        self.gridLayout_17.addWidget(self.widget_LID4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_LID4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_LID5 = Canvas(self.tab_5)
        self.widget_LID5.setObjectName("widget_LID5")
        self.gridLayout_16.addWidget(self.widget_LID5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.widget_LID6 = Canvas(self.tab_6)
        self.widget_LID6.setObjectName("widget_LID6")
        self.gridLayout_15.addWidget(self.widget_LID6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.widget_LID7 = Canvas(self.tab_7)
        self.widget_LID7.setObjectName("widget_LID7")
        self.gridLayout_14.addWidget(self.widget_LID7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget_LID8 = Canvas(self.tab_8)
        self.widget_LID8.setObjectName("widget_LID8")
        self.gridLayout_13.addWidget(self.widget_LID8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_LID_14 = Canvas(self.tab_11)
        self.widget_LID_14.setObjectName("widget_LID_14")
        self.gridLayout_12.addWidget(self.widget_LID_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_LID_58 = Canvas(self.tab_12)
        self.widget_LID_58.setObjectName("widget_LID_58")
        self.gridLayout_11.addWidget(self.widget_LID_58, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_LID_ALL = Canvas(self.tab_9)
        self.widget_LID_ALL.setObjectName("widget_LID_ALL")
        self.gridLayout_9.addWidget(self.widget_LID_ALL, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_MIR = Canvas(self.tab_10)
        self.widget_MIR.setObjectName("widget_MIR")
        self.gridLayout_10.addWidget(self.widget_MIR, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(600, 807))
        self.groupBox_8.setMaximumSize(QtCore.QSize(600, 807))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_jpn = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_jpn.setText("")
        self.lineEdit_jpn.setObjectName("lineEdit_jpn")
        self.gridLayout.addWidget(self.lineEdit_jpn, 1, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_jpn_seq = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_jpn_seq.setText("")
        self.lineEdit_jpn_seq.setObjectName("lineEdit_jpn_seq")
        self.gridLayout.addWidget(self.lineEdit_jpn_seq, 2, 1, 1, 2)
        self.checkBox_newpulse = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_newpulse.setObjectName("checkBox_newpulse")
        self.gridLayout.addWidget(self.checkBox_newpulse, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.comboBox_readuid = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_readuid.setEditable(True)
        self.comboBox_readuid.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_readuid.setObjectName("comboBox_readuid")
        self.gridLayout.addWidget(self.comboBox_readuid, 4, 2, 1, 1)
        self.button_read_pulse = QtWidgets.QPushButton(self.groupBox_3)
        self.button_read_pulse.setObjectName("button_read_pulse")
        self.gridLayout.addWidget(self.button_read_pulse, 5, 0, 1, 2)
        self.button_save = QtWidgets.QPushButton(self.groupBox_3)
        self.button_save.setObjectName("button_save")
        self.gridLayout.addWidget(self.button_save, 6, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_storeData = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_storeData.setObjectName("radioButton_storeData")
        self.gridLayout_3.addWidget(self.radioButton_storeData, 0, 0, 1, 1)
        self.radioButton_storeSF = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_storeSF.setObjectName("radioButton_storeSF")
        self.gridLayout_3.addWidget(self.radioButton_storeSF, 1, 0, 1, 1)
        self.checkBox_DS = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_DS.setObjectName("checkBox_DS")
        self.gridLayout_3.addWidget(self.checkBox_DS, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_writeuid = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_writeuid.setEditable(True)
        self.comboBox_writeuid.setObjectName("comboBox_writeuid")
        self.gridLayout_6.addWidget(self.comboBox_writeuid, 2, 0, 1, 1)
        self.button_saveppf = QtWidgets.QPushButton(self.groupBox)
        self.button_saveppf.setObjectName("button_saveppf")
        self.gridLayout_6.addWidget(self.button_saveppf, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBox_markers = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_markers.setObjectName("comboBox_markers")
        self.gridLayout_8.addWidget(self.comboBox_markers, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_2ndtrace = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_2ndtrace.setObjectName("comboBox_2ndtrace")
        self.gridLayout_7.addWidget(self.comboBox_2ndtrace, 0, 0, 1, 1)
        self.button_normalize = QtWidgets.QPushButton(self.groupBox_5)
        self.button_normalize.setObjectName("button_normalize")
        self.gridLayout_7.addWidget(self.button_normalize, 1, 0, 1, 1)
        self.button_restore = QtWidgets.QPushButton(self.groupBox_5)
        self.button_restore.setObjectName("button_restore")
        self.gridLayout_7.addWidget(self.button_restore, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.lineEdit_totcorr = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_totcorr.setObjectName("lineEdit_totcorr")
        self.gridLayout_21.addWidget(self.lineEdit_totcorr, 1, 0, 1, 2)
        self.widget_mancorr = QtWidgets.QWidget(self.groupBox_6)
        self.widget_mancorr.setObjectName("widget_mancorr")
        self.gridLayout_21.addWidget(self.widget_mancorr, 3, 0, 1, 2)
        self.pushButton_makeperm = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_makeperm.setObjectName("pushButton_makeperm")
        self.gridLayout_21.addWidget(self.pushButton_makeperm, 5, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_21.addWidget(self.label_4, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_21.addWidget(self.label_3, 0, 0, 1, 2)
        self.pushButton_undo = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.gridLayout_21.addWidget(self.pushButton_undo, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 2, 0, 2, 1)
        self.groupBox_statusflag = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_statusflag.setObjectName("groupBox_statusflag")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_statusflag)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_statusflag_3 = QtWidgets.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_3.setObjectName("radioButton_statusflag_3")
        self.gridLayout_5.addWidget(self.radioButton_statusflag_3, 0, 1, 1, 1)
        self.radioButton_statusflag_1 = QtWidgets.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_1.setObjectName("radioButton_statusflag_1")
        self.gridLayout_5.addWidget(self.radioButton_statusflag_1, 1, 0, 1, 1)
        self.radioButton_statusflag_4 = QtWidgets.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_4.setObjectName("radioButton_statusflag_4")
        self.gridLayout_5.addWidget(self.radioButton_statusflag_4, 1, 1, 1, 1)
        self.radioButton_statusflag_2 = QtWidgets.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_2.setObjectName("radioButton_statusflag_2")
        self.gridLayout_5.addWidget(self.radioButton_statusflag_2, 2, 0, 1, 1)
        self.radioButton_statusflag_0 = QtWidgets.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_0.setObjectName("radioButton_statusflag_0")
        self.gridLayout_5.addWidget(self.radioButton_statusflag_0, 0, 0, 1, 1)
        self.checkSFbutton = QtWidgets.QPushButton(self.groupBox_statusflag)
        self.checkSFbutton.setObjectName("checkSFbutton")
        self.gridLayout_5.addWidget(self.checkSFbutton, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_statusflag, 2, 1, 1, 1)
        self.exit_button = QtWidgets.QPushButton(self.groupBox_8)
        self.exit_button.setObjectName("exit_button")
        self.gridLayout_4.addWidget(self.exit_button, 3, 1, 1, 1)
        self.logger = QtWidgets.QWidget(self.groupBox_8)
        self.logger.setEnabled(True)
        self.logger.setAutoFillBackground(False)
        self.logger.setObjectName("logger")
        self.gridLayout_4.addWidget(self.logger, 4, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_8, 0, 1, 1, 1)
        CORMAT_py.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CORMAT_py)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1348, 20))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        CORMAT_py.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CORMAT_py)
        self.statusbar.setObjectName("statusbar")
        CORMAT_py.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(CORMAT_py)
        self.actionHelp.setObjectName("actionHelp")
        self.actionOpen_PDF_guide = QtWidgets.QAction(CORMAT_py)
        self.actionOpen_PDF_guide.setObjectName("actionOpen_PDF_guide")
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionOpen_PDF_guide)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CORMAT_py)
        self.tabWidget.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(CORMAT_py)

    def retranslateUi(self, CORMAT_py):
        _translate = QtCore.QCoreApplication.translate
        CORMAT_py.setWindowTitle(_translate("CORMAT_py", "CORMATpy"))
        self.tabWidget.setWhatsThis(_translate("CORMAT_py", "<html><head/><body><p>MIR</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID1), _translate("CORMAT_py", "LID1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID2), _translate("CORMAT_py", "LID2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID3), _translate("CORMAT_py", "LID3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID4), _translate("CORMAT_py", "LID4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("CORMAT_py", "LID5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("CORMAT_py", "LID6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("CORMAT_py", "LIF7"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("CORMAT_py", "LID8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("CORMAT_py", "LID 1-4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("CORMAT_py", "LID 5-8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("CORMAT_py", "LID ALL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("CORMAT_py", "MIR"))
        self.groupBox_8.setTitle(_translate("CORMAT_py", "CORMATpy"))
        self.groupBox_3.setTitle(_translate("CORMAT_py", "Input"))
        self.label_5.setText(_translate("CORMAT_py", "JPN"))
        self.label_6.setText(_translate("CORMAT_py", "sequence"))
        self.checkBox_newpulse.setText(_translate("CORMAT_py", "New pulse"))
        self.label.setText(_translate("CORMAT_py", "read uid"))
        self.button_read_pulse.setText(_translate("CORMAT_py", "Load"))
        self.button_save.setText(_translate("CORMAT_py", "SAVE WORKSPACE"))
        self.groupBox.setTitle(_translate("CORMAT_py", "Output"))
        self.groupBox_2.setTitle(_translate("CORMAT_py", "Record data"))
        self.radioButton_storeData.setText(_translate("CORMAT_py", "Data"))
        self.radioButton_storeSF.setText(_translate("CORMAT_py", "Status Flag"))
        self.checkBox_DS.setText(_translate("CORMAT_py", "downsample"))
        self.label_2.setText(_translate("CORMAT_py", "write uid"))
        self.button_saveppf.setText(_translate("CORMAT_py", "WRITE PPF"))
        self.groupBox_9.setTitle(_translate("CORMAT_py", "Markers"))
        self.groupBox_5.setTitle(_translate("CORMAT_py", "Second Trace"))
        self.button_normalize.setText(_translate("CORMAT_py", "normalize"))
        self.button_restore.setText(_translate("CORMAT_py", "restore"))
        self.groupBox_6.setTitle(_translate("CORMAT_py", "Corrections"))
        self.pushButton_makeperm.setText(_translate("CORMAT_py", "Make Permanent"))
        self.label_4.setText(_translate("CORMAT_py", "Manual Correction"))
        self.label_3.setText(_translate("CORMAT_py", "Total Corrections"))
        self.pushButton_undo.setText(_translate("CORMAT_py", "Undo"))
        self.groupBox_statusflag.setTitle(_translate("CORMAT_py", "Status Flag"))
        self.radioButton_statusflag_3.setText(_translate("CORMAT_py", "3"))
        self.radioButton_statusflag_1.setText(_translate("CORMAT_py", "1"))
        self.radioButton_statusflag_4.setText(_translate("CORMAT_py", "4"))
        self.radioButton_statusflag_2.setText(_translate("CORMAT_py", "2"))
        self.radioButton_statusflag_0.setText(_translate("CORMAT_py", "0"))
        self.checkSFbutton.setText(_translate("CORMAT_py", "check SF"))
        self.exit_button.setText(_translate("CORMAT_py", "EXIT"))
        self.menuHelp.setTitle(_translate("CORMAT_py", "Help"))
        self.actionHelp.setText(_translate("CORMAT_py", "Help"))
        self.actionOpen_PDF_guide.setText(_translate("CORMAT_py", "Open PDF guide"))
from canvas import Canvas
