# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_woop_layout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CORMAT_py(object):
    def setupUi(self, CORMAT_py):
        CORMAT_py.setObjectName(_fromUtf8("CORMAT_py"))
        CORMAT_py.resize(1159, 844)
        self.centralwidget = QtGui.QWidget(CORMAT_py)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setMaximumSize(QtCore.QSize(359, 807))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_jpn = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_jpn.setText(_fromUtf8(""))
        self.lineEdit_jpn.setObjectName(_fromUtf8("lineEdit_jpn"))
        self.gridLayout.addWidget(self.lineEdit_jpn, 0, 0, 1, 2)
        self.checkBox_newpulse = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_newpulse.setObjectName(_fromUtf8("checkBox_newpulse"))
        self.gridLayout.addWidget(self.checkBox_newpulse, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.comboBox_readuid = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_readuid.setEditable(True)
        self.comboBox_readuid.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.comboBox_readuid.setObjectName(_fromUtf8("comboBox_readuid"))
        self.gridLayout.addWidget(self.comboBox_readuid, 2, 1, 1, 1)
        self.button_read_pulse = QtGui.QPushButton(self.groupBox_3)
        self.button_read_pulse.setObjectName(_fromUtf8("button_read_pulse"))
        self.gridLayout.addWidget(self.button_read_pulse, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButton_storeData = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_storeData.setObjectName(_fromUtf8("radioButton_storeData"))
        self.gridLayout_3.addWidget(self.radioButton_storeData, 0, 0, 1, 1)
        self.radioButton_storeSF = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_storeSF.setObjectName(_fromUtf8("radioButton_storeSF"))
        self.gridLayout_3.addWidget(self.radioButton_storeSF, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_writeuid = QtGui.QComboBox(self.groupBox)
        self.comboBox_writeuid.setEditable(True)
        self.comboBox_writeuid.setObjectName(_fromUtf8("comboBox_writeuid"))
        self.gridLayout_6.addWidget(self.comboBox_writeuid, 2, 0, 1, 1)
        self.button_save = QtGui.QPushButton(self.groupBox)
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.gridLayout_6.addWidget(self.button_save, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.comboBox_markers = QtGui.QComboBox(self.groupBox_9)
        self.comboBox_markers.setObjectName(_fromUtf8("comboBox_markers"))
        self.gridLayout_8.addWidget(self.comboBox_markers, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_2ndtrace = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_2ndtrace.setObjectName(_fromUtf8("comboBox_2ndtrace"))
        self.gridLayout_7.addWidget(self.comboBox_2ndtrace, 0, 0, 1, 1)
        self.button_normalize = QtGui.QPushButton(self.groupBox_5)
        self.button_normalize.setObjectName(_fromUtf8("button_normalize"))
        self.gridLayout_7.addWidget(self.button_normalize, 1, 0, 1, 1)
        self.button_restore = QtGui.QPushButton(self.groupBox_5)
        self.button_restore.setObjectName(_fromUtf8("button_restore"))
        self.gridLayout_7.addWidget(self.button_restore, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_totcorr = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_totcorr.setObjectName(_fromUtf8("lineEdit_totcorr"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lineEdit_totcorr)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_mancorr = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_mancorr.setObjectName(_fromUtf8("lineEdit_mancorr"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineEdit_mancorr)
        self.pushButton_apply = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_apply.setObjectName(_fromUtf8("pushButton_apply"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_apply)
        self.pushButton_undo = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_undo.setObjectName(_fromUtf8("pushButton_undo"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.pushButton_undo)
        self.pushButton_makeperm = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_makeperm.setObjectName(_fromUtf8("pushButton_makeperm"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.pushButton_makeperm)
        self.gridLayout_4.addWidget(self.groupBox_6, 2, 0, 2, 1)
        self.groupBox_statusflag = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_statusflag.setObjectName(_fromUtf8("groupBox_statusflag"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_statusflag)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radioButton_statusflag_3 = QtGui.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_3.setObjectName(_fromUtf8("radioButton_statusflag_3"))
        self.gridLayout_5.addWidget(self.radioButton_statusflag_3, 0, 1, 1, 1)
        self.radioButton_statusflag_1 = QtGui.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_1.setObjectName(_fromUtf8("radioButton_statusflag_1"))
        self.gridLayout_5.addWidget(self.radioButton_statusflag_1, 1, 0, 1, 1)
        self.radioButton_statusflag_4 = QtGui.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_4.setObjectName(_fromUtf8("radioButton_statusflag_4"))
        self.gridLayout_5.addWidget(self.radioButton_statusflag_4, 1, 1, 1, 1)
        self.radioButton_statusflag_2 = QtGui.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_2.setObjectName(_fromUtf8("radioButton_statusflag_2"))
        self.gridLayout_5.addWidget(self.radioButton_statusflag_2, 2, 0, 1, 1)
        self.radioButton_statusflag_0 = QtGui.QRadioButton(self.groupBox_statusflag)
        self.radioButton_statusflag_0.setObjectName(_fromUtf8("radioButton_statusflag_0"))
        self.gridLayout_5.addWidget(self.radioButton_statusflag_0, 0, 0, 1, 1)
        self.checkSFbutton = QtGui.QPushButton(self.groupBox_statusflag)
        self.checkSFbutton.setObjectName(_fromUtf8("checkSFbutton"))
        self.gridLayout_5.addWidget(self.checkSFbutton, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_statusflag, 2, 1, 1, 1)
        self.exit_button = QtGui.QPushButton(self.groupBox_8)
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.gridLayout_4.addWidget(self.exit_button, 3, 1, 1, 1)
        self.logger = QtGui.QWidget(self.groupBox_8)
        self.logger.setEnabled(True)
        self.logger.setAutoFillBackground(False)
        self.logger.setObjectName(_fromUtf8("logger"))
        self.gridLayout_4.addWidget(self.logger, 4, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(724, 807))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_LID1 = QtGui.QWidget()
        self.tab_LID1.setObjectName(_fromUtf8("tab_LID1"))
        self.widget_LID1 = Canvas(self.tab_LID1)
        self.widget_LID1.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID1.setObjectName(_fromUtf8("widget_LID1"))
        self.tabWidget.addTab(self.tab_LID1, _fromUtf8(""))
        self.tab_LID2 = QtGui.QWidget()
        self.tab_LID2.setObjectName(_fromUtf8("tab_LID2"))
        self.widget_LID2 = Canvas(self.tab_LID2)
        self.widget_LID2.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID2.setObjectName(_fromUtf8("widget_LID2"))
        self.tabWidget.addTab(self.tab_LID2, _fromUtf8(""))
        self.tab_LID3 = QtGui.QWidget()
        self.tab_LID3.setObjectName(_fromUtf8("tab_LID3"))
        self.widget_LID3 = Canvas(self.tab_LID3)
        self.widget_LID3.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID3.setObjectName(_fromUtf8("widget_LID3"))
        self.tabWidget.addTab(self.tab_LID3, _fromUtf8(""))
        self.tab_LID4 = QtGui.QWidget()
        self.tab_LID4.setObjectName(_fromUtf8("tab_LID4"))
        self.widget_LID4 = Canvas(self.tab_LID4)
        self.widget_LID4.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID4.setObjectName(_fromUtf8("widget_LID4"))
        self.tabWidget.addTab(self.tab_LID4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.widget_LID5 = Canvas(self.tab_5)
        self.widget_LID5.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID5.setObjectName(_fromUtf8("widget_LID5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.widget_LID6 = Canvas(self.tab_6)
        self.widget_LID6.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID6.setObjectName(_fromUtf8("widget_LID6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.widget_LID7 = Canvas(self.tab_7)
        self.widget_LID7.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID7.setObjectName(_fromUtf8("widget_LID7"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.widget_LID8 = Canvas(self.tab_8)
        self.widget_LID8.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID8.setObjectName(_fromUtf8("widget_LID8"))
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.widget_LID_14 = Canvas(self.tab_11)
        self.widget_LID_14.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID_14.setObjectName(_fromUtf8("widget_LID_14"))
        self.tabWidget.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.widget_LID_58 = Canvas(self.tab_12)
        self.widget_LID_58.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID_58.setObjectName(_fromUtf8("widget_LID_58"))
        self.tabWidget.addTab(self.tab_12, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.widget_LID_ALL = Canvas(self.tab_9)
        self.widget_LID_ALL.setGeometry(QtCore.QRect(0, 0, 1041, 781))
        self.widget_LID_ALL.setObjectName(_fromUtf8("widget_LID_ALL"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_10)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.widget_MIR = Canvas(self.tab_10)
        self.widget_MIR.setObjectName(_fromUtf8("widget_MIR"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.widget_MIR)
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        CORMAT_py.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CORMAT_py)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1159, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        CORMAT_py.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CORMAT_py)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CORMAT_py.setStatusBar(self.statusbar)
        self.actionHelp = QtGui.QAction(CORMAT_py)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionOpen_PDF_guide = QtGui.QAction(CORMAT_py)
        self.actionOpen_PDF_guide.setObjectName(_fromUtf8("actionOpen_PDF_guide"))
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionOpen_PDF_guide)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CORMAT_py)
        self.tabWidget.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(CORMAT_py)

    def retranslateUi(self, CORMAT_py):
        CORMAT_py.setWindowTitle(_translate("CORMAT_py", "CORMATpy", None))
        self.groupBox_8.setTitle(_translate("CORMAT_py", "CORMATpy", None))
        self.groupBox_3.setTitle(_translate("CORMAT_py", "Input", None))
        self.checkBox_newpulse.setText(_translate("CORMAT_py", "New pulse", None))
        self.label.setText(_translate("CORMAT_py", "read uid", None))
        self.button_read_pulse.setText(_translate("CORMAT_py", "Load", None))
        self.groupBox.setTitle(_translate("CORMAT_py", "Output", None))
        self.groupBox_2.setTitle(_translate("CORMAT_py", "Record data", None))
        self.radioButton_storeData.setText(_translate("CORMAT_py", "Data", None))
        self.radioButton_storeSF.setText(_translate("CORMAT_py", "Status Flag", None))
        self.label_2.setText(_translate("CORMAT_py", "write uid", None))
        self.button_save.setText(_translate("CORMAT_py", "Save", None))
        self.groupBox_9.setTitle(_translate("CORMAT_py", "Markers", None))
        self.groupBox_5.setTitle(_translate("CORMAT_py", "Second Trace", None))
        self.button_normalize.setText(_translate("CORMAT_py", "normalize", None))
        self.button_restore.setText(_translate("CORMAT_py", "restore", None))
        self.groupBox_6.setTitle(_translate("CORMAT_py", "Corrections", None))
        self.label_3.setText(_translate("CORMAT_py", "Total Corrections", None))
        self.label_4.setText(_translate("CORMAT_py", "Manual Correction", None))
        self.pushButton_apply.setText(_translate("CORMAT_py", "Apply", None))
        self.pushButton_undo.setText(_translate("CORMAT_py", "Undo", None))
        self.pushButton_makeperm.setText(_translate("CORMAT_py", "Make Permanent", None))
        self.groupBox_statusflag.setTitle(_translate("CORMAT_py", "Status Flag", None))
        self.radioButton_statusflag_3.setText(_translate("CORMAT_py", "3", None))
        self.radioButton_statusflag_1.setText(_translate("CORMAT_py", "1", None))
        self.radioButton_statusflag_4.setText(_translate("CORMAT_py", "4", None))
        self.radioButton_statusflag_2.setText(_translate("CORMAT_py", "2", None))
        self.radioButton_statusflag_0.setText(_translate("CORMAT_py", "0", None))
        self.checkSFbutton.setText(_translate("CORMAT_py", "check SF", None))
        self.exit_button.setText(_translate("CORMAT_py", "exit", None))
        self.tabWidget.setWhatsThis(_translate("CORMAT_py", "<html><head/><body><p>LID1</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID1), _translate("CORMAT_py", "LID1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID2), _translate("CORMAT_py", "LID2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID3), _translate("CORMAT_py", "LID3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LID4), _translate("CORMAT_py", "LID4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("CORMAT_py", "LID5", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("CORMAT_py", "LID6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("CORMAT_py", "LIF7", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("CORMAT_py", "LID8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("CORMAT_py", "LID 1-4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("CORMAT_py", "LID 5-8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("CORMAT_py", "LID ALL", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("CORMAT_py", "MIR", None))
        self.menuHelp.setTitle(_translate("CORMAT_py", "Help", None))
        self.actionHelp.setText(_translate("CORMAT_py", "Help", None))
        self.actionOpen_PDF_guide.setText(_translate("CORMAT_py", "Open PDF guide", None))

from canvas import Canvas
